-- Medida: [Ranking de Ventas por Producto]
-- Objetivo: Clasificar los productos por ventas totales.
-- L贸gica:
-- 1. Itera sobre *todos* los productos.
-- 2. Calcula las ventas totales para *cada* producto.
-- 3. Clasifica los productos en funci贸n de estas ventas totales.

[Ranking de Ventas por Producto] =
RANKX (
    ALL (Products[ProductName]),
    [Total Ventas],  -- Asume que tienes una medida llamada [Total Ventas]
    ,   -- Opcional: Especifica el orden (ASC o DESC). Si se omite, es DESC.
    ,   -- Opcional: Especifica c贸mo manejar los empates (SKIP o DENSE). Si se omite, es SKIP.
    DESC
)

-- Consideraciones:
-- - RANKX es una funci贸n iteradora.
-- - ALL() es muy importante para eliminar los filtros.