-- Medida: [Margen de Ganancia]
-- Objetivo: Calcular el margen de ganancia (Ganancia / Ventas), manejando la divisi칩n por cero.
-- L칩gica:
-- Divide las 'Ventas' por el 'Costo', y si el 'Costo' es cero, devuelve 0.

[Margen de Ganancia] =
DIVIDE (
    SUM (Sales[Profit]),
    SUM (Sales[SalesAmount]),
    0
)

-- Consideraciones:
-- - DIVIDE es la forma recomendada de dividir en DAX, ya que maneja autom치ticamente la divisi칩n por cero.